version: 2
updates:
  - package-ecosystem: nuget
    directory: /src/T2TouchBar
    schedule:
      interval: monthly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
